# Generated by Django 5.1 on 2024-08-26 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='date_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
