# Generated by Django 5.1 on 2025-10-27 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotaconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotaconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
