# Generated by Django 5.1 on 2025-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_quotaconfig_created_at_quotaconfig_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotaconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotaconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='quotaconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
