# Generated by Django 5.1 on 2025-11-24 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'due_date'], name='payments_pa_user_id_aa2b55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date', 'is_fully_paid'], name='payments_pa_due_dat_539a36_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'is_fully_paid'], name='payments_pa_user_id_9e58bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date'], name='payments_pa_due_dat_752274_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_paid', 'is_fully_paid'], name='payments_pa_is_paid_5935a4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'transaction_date'], name='payments_pa_payment_29d526_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_date'], name='payments_pa_transac_2ad7c5_idx'),
        ),
    ]
