"""
Django settings for martial_arts_api project.

Generated by 'django-admin startproject' using Django 5.1.
"""

from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse
from celery.schedules import crontab
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-s@@ksa+i2$#!^a-5r6hbxl-wvzxefn!&o)m8j#@s%h@_-oiyi=')

# DEBUG: False por defecto en producción (más seguro)
# Cambiar a True solo para desarrollo local
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS - Configuración desde variable de entorno o lista por defecto
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # En desarrollo, permitir localhost
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if DEBUG else []

# Agregar automáticamente dominios de Railway si se detecta que estamos en Railway
# Django no soporta wildcards directamente, así que usamos una validación dinámica
if not DEBUG:
    # Detectar si estamos en Railway
    is_railway = (
        os.getenv('RAILWAY_ENVIRONMENT') is not None or
        os.getenv('RAILWAY_SERVICE_NAME') is not None or
        'railway.app' in str(ALLOWED_HOSTS_ENV).lower()
    )
    
    if is_railway or not ALLOWED_HOSTS_ENV:
        # Agregar automáticamente healthcheck.railway.app (dominio interno de Railway)
        # El dominio principal debe agregarse en la variable de entorno ALLOWED_HOSTS en Railway
        railway_domains = [
            'healthcheck.railway.app',  # Dominio interno de Railway para healthchecks
        ]
        
        for domain in railway_domains:
            if domain not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(domain)
                ALLOWED_HOSTS.append(domain)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'payments',
    'blog',
    'classes',
    'resources',
    'gallery',
    'performance',
    'contact',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    'corsheaders',
    # Tiempo real
    'channels',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Debe ir después de SecurityMiddleware
    # 'martial_arts_api.middleware.HealthCheckMiddleware',  # Deshabilitado: el middleware ASGI maneja /health/
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'martial_arts_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'martial_arts_api.wsgi.application'
ASGI_APPLICATION = 'martial_arts_api.asgi.application'

# Configuración de base de datos
# Soporta configuración desde variable de entorno (Docker) o valores por defecto
DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    # Parsear DATABASE_URL usando urlparse para manejar mejor los casos edge
    from urllib.parse import urlparse, parse_qs, unquote
    
    try:
        parsed = urlparse(DATABASE_URL)
        
        # Extraer componentes
        db_user = unquote(parsed.username) if parsed.username else ''
        db_password = unquote(parsed.password) if parsed.password else ''
        db_host = parsed.hostname or ''
        db_port = str(parsed.port) if parsed.port else '5432'
        # El nombre de la base de datos está en el path, sin el '/' inicial
        db_name = parsed.path.lstrip('/') if parsed.path else ''
        # Si hay parámetros de query, parsearlos
        params = parse_qs(parsed.query)
        
        # Limpiar el nombre de la base de datos (puede tener parámetros)
        if '?' in db_name:
            db_name = db_name.split('?')[0]
        
        # Detectar si es Supabase (requiere SSL)
        is_supabase = 'supabase' in db_host.lower()
        
        # Configuración base
        db_config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        }
        
        # Configurar SSL para Supabase
        if is_supabase:
            db_config['OPTIONS'] = {
                'sslmode': 'require',
            }
            # Si hay parámetros SSL en la URL, usarlos
            if 'sslmode' in params:
                db_config['OPTIONS']['sslmode'] = params['sslmode'][0]
        
        DATABASES = {
            'default': db_config
        }
    except Exception as e:
        # Si falla el parseo, intentar método antiguo como fallback
        import re
        match = re.match(r'postgresql://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)', DATABASE_URL)
        if match:
            db_user, db_password, db_host, db_port, db_name = match.groups()
            # Limpiar nombre de base de datos
            if '?' in db_name:
                db_name = db_name.split('?')[0]
            
            is_supabase = 'supabase' in db_host.lower()
            
            db_config = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': db_host,
                'PORT': db_port,
            }
            
            if is_supabase:
                db_config['OPTIONS'] = {
                    'sslmode': 'require',
                }
            
            DATABASES = {
                'default': db_config
            }
        else:
            # Fallback a configuración por defecto si no se puede parsear
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': 'martial_arts_db',
                    'USER': 'martial_user',
                    'PASSWORD': 'abc12345',
                    'HOST': os.getenv('DB_HOST', 'localhost'),
                    'PORT': os.getenv('DB_PORT', '5432'),
                }
            }
else:
    # Configuración por defecto (desarrollo local)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'martial_arts_db'),
            'USER': os.getenv('DB_USER', 'martial_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'abc12345'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'es-es')

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

# Configuración de Redis (compartida por Channels y Celery)
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/1')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')

if not REDIS_HOST or not REDIS_PORT:
    parsed_redis = urlparse(REDIS_URL)
    REDIS_HOST = REDIS_HOST or (parsed_redis.hostname or 'localhost')
    REDIS_PORT = REDIS_PORT or (parsed_redis.port or 6379)

REDIS_PORT = int(REDIS_PORT)

USE_I18N = True

USE_TZ = True

# APPEND_SLASH: True por defecto, pero el middleware maneja /health sin redirecciones
APPEND_SLASH = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de WhiteNoise para servir archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Throttling y Rate Limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/hour',  # Usuarios autenticados: 1000 requests por hora
        'anon': '100/hour',    # Usuarios anónimos: 100 requests por hora
        'login': '5/minute',   # Login: 5 intentos por minuto
        'register': '3/hour',   # Registro: 3 intentos por hora
        'password_reset': '3/hour',  # Reset de contraseña: 3 intentos por hora
        'password_reset_confirm': '5/hour',  # Confirmación de reset: 5 intentos por hora
        'sensitive': '20/hour',  # Endpoints sensibles: 20 requests por hora
        'brute_force': '10/minute',  # Protección contra fuerza bruta: 10 intentos por minuto
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Configuración de Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Configuración de Celery Beat (tareas programadas)
CELERY_BEAT_SCHEDULE = {
    # Generar cuotas anuales cada enero
    'generar-cuotas-anuales-cada-enero': {
        'task': 'martial_arts_api.tasks.generate_annual_payments_for_all_students',
        'schedule': crontab(minute=0, hour=0, day_of_month=1, month_of_year=1),  # 1 de enero a las 00:00
    },
    # Generar cuotas mensuales el día 1 de cada mes
    'generar-cuotas-mensuales': {
        'task': 'payments.tasks.generate_monthly_payments_task',
        'schedule': crontab(minute=0, hour=8, day_of_month=1),  # Día 1 de cada mes a las 08:00
    },
    # Enviar recordatorios de clases cada 15 minutos
    'send-class-reminders': {
        'task': 'notifications.tasks.send_class_reminders_task',
        'schedule': crontab(minute='*/15'),  # Cada 15 minutos
    },
    # Notificar pagos vencidos diariamente
    'notify-overdue-payments': {
        'task': 'payments.tasks.notify_overdue_payments',
        'schedule': crontab(minute=0, hour=9),  # Todos los días a las 09:00
    },
    # Notificar pagos próximos a vencer diariamente
    'notify-upcoming-payments': {
        'task': 'payments.tasks.notify_upcoming_payments',
        'schedule': crontab(minute=0, hour=9),  # Todos los días a las 09:00
    },
    # Generar reporte mensual (se ejecuta diariamente, pero solo genera reporte el último día del mes)
    'generate-monthly-report': {
        'task': 'payments.tasks.generate_monthly_report',
        'schedule': crontab(minute=0, hour=10, day_of_month='28,29,30,31'),  # Días 28-31 a las 10:00 (la tarea verifica si es el último día)
    },
}

# Configuración de CORS
# En desarrollo, permitir todos los orígenes para facilitar el desarrollo
# En producción, usar solo orígenes específicos
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Función para limpiar URLs (quitar paths y barras finales)
def clean_origin_url(url):
    """Limpia una URL para usar como origen CORS (solo dominio, sin path)"""
    if not url:
        return None
    url = url.strip()
    # Quitar barras finales
    url = url.rstrip('/')
    # Si tiene path (después de /), extraer solo el dominio
    parsed = urlparse(url)
    # Construir solo el esquema + netloc (dominio)
    clean_url = f"{parsed.scheme}://{parsed.netloc}"
    return clean_url

# Orígenes permitidos (solo se usan si CORS_ALLOW_ALL_ORIGINS = False)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Agregar aquí los dominios de producción cuando estén disponibles
    # "https://tu-dominio.com",
    # "https://www.tu-dominio.com",
]

# Si CORS_ALLOWED_ORIGINS está configurado como variable de entorno, agregarlo
CORS_ALLOWED_ORIGINS_ENV = os.getenv('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    # Puede ser una lista separada por comas
    origins = [clean_origin_url(origin.strip()) for origin in CORS_ALLOWED_ORIGINS_ENV.split(',') if origin.strip()]
    # Agregar solo los que se limpiaron correctamente
    for origin in origins:
        if origin and origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

# Permitir orígenes con regex (útil para subdominios)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.tu-dominio\.com$",  # Ejemplo: permite cualquier subdominio
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Headers permitidos en las solicitudes CORS
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",  # Necesario para JWT
    "content-type",
    "content-disposition",  # Para descargas de archivos
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-forwarded-for",  # Para proxies
    "x-forwarded-proto",  # Para proxies
    "cache-control",  # Para control de caché
    "pragma",  # Para control de caché
]

# Headers expuestos al frontend
CORS_EXPOSE_HEADERS = [
    "content-type",
    "content-disposition",
    "content-length",
    "x-total-count",  # Útil para paginación
]

# Permitir credenciales (cookies, headers de autorización, etc.)
CORS_ALLOW_CREDENTIALS = True

# Tiempo máximo de caché para preflight requests (en segundos)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 horas

AUTHENTICATION_BACKENDS = (
    'users.backends.EmailBackend',
)

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False

# Configuración de Caché (usando Redis para throttling y rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # PARSER_CLASS removido - django-redis usará el parser por defecto automáticamente
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'martial_arts',
        'TIMEOUT': 300,  # 5 minutos por defecto
    }
}

# Tiempo de caché por defecto (en segundos)
CACHE_TTL = 60 * 15  # 15 minutos

# URL del frontend para enlaces de restablecimiento de contraseña
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Si FRONTEND_URL está configurado y no está en DEBUG, agregarlo a CORS_ALLOWED_ORIGINS
# (en DEBUG, CORS_ALLOW_ALL_ORIGINS ya permite todos los orígenes)
if not DEBUG and FRONTEND_URL:
    clean_frontend_url = clean_origin_url(FRONTEND_URL)
    if clean_frontend_url and clean_frontend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(clean_frontend_url)

# Configuración de correo electrónico
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tu_correo@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu_contraseña')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Martial Arts <tu_correo@gmail.com>')

# Configuración de archivos media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Channels - Configuración de capas de canal (Redis por defecto)

# Para desarrollo, usar InMemoryChannelLayer si Redis no está disponible
# Para producción, usar RedisChannelLayer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    }
}

# Fallback a InMemoryChannelLayer si Redis no está disponible (solo para desarrollo)
# Descomentar si Redis no está disponible:
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

# ============================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# ============================================

if not DEBUG:
    # Seguridad HTTPS
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Protección adicional
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Configuración de sesiones
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    # Configuración CSRF
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Si usas un proxy reverso (como Nginx), descomenta:
    # USE_X_FORWARDED_HOST = True
    # USE_X_FORWARDED_PORT = True