# Generated by Django 5.1 on 2024-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
