# Generated by Django 5.1 on 2025-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='users_userp_role_c31a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'role'], name='users_userp_user_id_71ac48_idx'),
        ),
    ]
