# Generated by Django 5.1 on 2025-11-29 18:44

import django.db.models.deletion
from django.db import migrations, models


def clean_empty_dojo_values(apps, schema_editor):
    """Convierte todos los valores de texto de dojo a NULL ya que no se pueden mapear automáticamente a ForeignKey"""
    # Usar SQL directo para convertir TODOS los valores de texto a NULL
    # Esto es necesario porque no podemos convertir strings a IDs de ForeignKey automáticamente
    with schema_editor.connection.cursor() as cursor:
        # Establecer NULL para TODOS los valores (vacíos y no vacíos)
        # Los usuarios podrán asignar manualmente las academias después de la migración
        cursor.execute("""
            UPDATE users_userprofile 
            SET dojo = NULL
        """)


def reverse_clean_empty_dojo_values(apps, schema_editor):
    """Función reversa - no necesitamos hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_academy'),
        ('users', '0007_userprofile_users_userp_role_c31a7e_idx_and_more'),
    ]

    operations = [
        # Paso 1: Hacer el campo nullable primero
        migrations.AlterField(
            model_name='userprofile',
            name='dojo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Paso 2: Limpiar valores vacíos
        migrations.RunPython(clean_empty_dojo_values, reverse_clean_empty_dojo_values),
        # Paso 3: Cambiar el tipo de campo a ForeignKey
        migrations.AlterField(
            model_name='userprofile',
            name='dojo',
            field=models.ForeignKey(blank=True, help_text='Academia a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='contact.academy', verbose_name='Academia'),
        ),
    ]
