# Generated by Django 5.1 on 2025-11-29 18:57

import django.db.models.deletion
from django.db import migrations, models


def clean_empty_belt_rank_values(apps, schema_editor):
    """Convierte todos los valores de texto de belt_rank a NULL ya que no se pueden mapear automáticamente a ForeignKey"""
    # Usar SQL directo para convertir TODOS los valores de texto a NULL
    # Esto es necesario porque no podemos convertir strings a IDs de ForeignKey automáticamente
    with schema_editor.connection.cursor() as cursor:
        # Establecer NULL para TODOS los valores (vacíos y no vacíos)
        # Los usuarios podrán asignar manualmente los cinturones después de la migración
        cursor.execute("""
            UPDATE users_userprofile 
            SET belt_rank = NULL
        """)


def reverse_clean_empty_belt_rank_values(apps, schema_editor):
    """Función reversa - no necesitamos hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_examresult_passed_alter_examsession_belt_level_and_more'),
        ('users', '0008_alter_userprofile_dojo'),
    ]

    operations = [
        # Paso 1: Hacer el campo nullable primero
        migrations.AlterField(
            model_name='userprofile',
            name='belt_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Paso 2: Limpiar todos los valores de texto
        migrations.RunPython(clean_empty_belt_rank_values, reverse_clean_empty_belt_rank_values),
        # Paso 3: Cambiar el tipo de campo a ForeignKey
        migrations.AlterField(
            model_name='userprofile',
            name='belt_rank',
            field=models.ForeignKey(blank=True, help_text='Cinturón actual del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='performance.beltrank', verbose_name='Cinturón'),
        ),
    ]
