# Generated by Django 5.1 on 2025-02-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclassreservation',
            options={'verbose_name': 'Reserva de clase', 'verbose_name_plural': 'Reservas de clases'},
        ),
    ]
