# Generated by Django 5.1 on 2025-02-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_userclassreservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
    ]
