# Generated by Django 5.1 on 2025-02-06 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='class',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
    ]
