# Generated by Django 5.1 on 2025-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_duration_class_reservation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclassreservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
