# Generated by Django 5.1 on 2025-10-29 18:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_userclassreservation_is_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('class_type', models.CharField(choices=[('regular', 'Regular'), ('intensive', 'Intensiva'), ('private', 'Privada'), ('seminar', 'Seminario'), ('exam', 'Examen')], default='regular', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('all_levels', 'Todos los niveles')], default='all_levels', max_length=20)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('max_students', models.IntegerField(default=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('equipment_needed', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de clase',
                'verbose_name_plural': 'Plantillas de clases',
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_reserved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Usuario que marcó la asistencia (instructor/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia de clase',
                'verbose_name_plural': 'Asistencias de clases',
                'indexes': [models.Index(fields=['class_reserved', 'attended'], name='classes_cla_class_r_896b8e_idx'), models.Index(fields=['user', 'attended'], name='classes_cla_user_id_afd475_idx')],
                'unique_together': {('class_reserved', 'user')},
            },
        ),
    ]
