# Generated by Django 5.1 on 2025-11-16 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_additional_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='qr_code_token',
            field=models.CharField(blank=True, help_text='Token único para el código QR de check-in', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ClassWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, help_text='Posición en la lista de espera')),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('notified', 'Notificado'), ('converted', 'Convertido a reserva'), ('cancelled', 'Cancelado')], default='waiting', help_text='Estado en la lista de espera', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se unió a la lista de espera')),
                ('notified_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue notificado de un cupo disponible', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se convirtió en reserva', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la entrada en la lista de espera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_reserved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='classes.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_waitlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de espera de clase',
                'verbose_name_plural': 'Listas de espera de clases',
                'ordering': ['position', 'joined_at'],
                'indexes': [models.Index(fields=['class_reserved', 'status'], name='classes_cla_class_r_4c3359_idx'), models.Index(fields=['user', 'status'], name='classes_cla_user_id_18b465_idx'), models.Index(fields=['position'], name='classes_cla_positio_1d074d_idx')],
                'unique_together': {('user', 'class_reserved')},
            },
        ),
    ]
