# Generated by Django 5.1 on 2025-11-24 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_class_qr_code_token_classwaitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['date'], name='classes_cla_date_966f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['instructor', 'date'], name='classes_cla_instruc_37b453_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_cancelled', 'date'], name='classes_cla_is_canc_bc64b3_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['class_type', 'date'], name='classes_cla_class_t_da3cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['difficulty_level'], name='classes_cla_difficu_3d4387_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['date', 'is_cancelled'], name='classes_cla_date_7c1104_idx'),
        ),
        migrations.AddIndex(
            model_name='userclassreservation',
            index=models.Index(fields=['user', 'created_at'], name='classes_use_user_id_46a811_idx'),
        ),
        migrations.AddIndex(
            model_name='userclassreservation',
            index=models.Index(fields=['class_reserved', 'is_cancelled'], name='classes_use_class_r_90a440_idx'),
        ),
        migrations.AddIndex(
            model_name='userclassreservation',
            index=models.Index(fields=['created_at'], name='classes_use_created_595457_idx'),
        ),
        migrations.AddIndex(
            model_name='userclassreservation',
            index=models.Index(fields=['is_cancelled'], name='classes_use_is_canc_328e4b_idx'),
        ),
    ]
