# Generated by Django 5.1 on 2025-02-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Galería', 'verbose_name_plural': 'Galerías'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Elemento de Galería', 'verbose_name_plural': 'Elementos de Galería'},
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
