# Generated by Django 5.1 on 2024-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeltExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_level', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Belt Exam',
                'verbose_name_plural': 'Belt Exams',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('First Place', 'First Place'), ('Second Place', 'Second Place'), ('Third Place', 'Third Place'), ('Exhibition', 'Exhibition')], max_length=20)),
                ('event_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamParameterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_attended', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Statistic',
                'verbose_name_plural': 'Performance Statistics',
            },
        ),
    ]
