# Generated by Django 5.1 on 2024-08-26 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='beltexam',
            options={'ordering': ['exam_date'], 'verbose_name': 'Belt Exam', 'verbose_name_plural': 'Belt Exams'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'ordering': ['event_date'], 'verbose_name': 'Event Participation', 'verbose_name_plural': 'Event Participations'},
        ),
        migrations.AlterModelOptions(
            name='performancestatistics',
            options={'verbose_name': 'Performance Statistic', 'verbose_name_plural': 'Performance Statistics'},
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='discipline',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='disciplines',
            field=models.ManyToManyField(related_name='event_participations', to='performance.discipline'),
        ),
        migrations.RemoveField(
            model_name='beltexam',
            name='parameters_evaluated',
        ),
        migrations.AlterField(
            model_name='performancestatistics',
            name='belt_exams',
            field=models.ManyToManyField(blank=True, related_name='performance_statistics', to='performance.beltexam'),
        ),
        migrations.AlterField(
            model_name='performancestatistics',
            name='event_participations',
            field=models.ManyToManyField(blank=True, related_name='performance_statistics', to='performance.eventparticipation'),
        ),
        migrations.AlterField(
            model_name='performancestatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExamParameterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.beltexam')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.evaluationparameter')),
            ],
        ),
        migrations.AddField(
            model_name='beltexam',
            name='parameters_evaluated',
            field=models.ManyToManyField(related_name='belt_exams', through='performance.ExamParameterScore', to='performance.evaluationparameter'),
        ),
    ]
