# Generated by Django 5.1 on 2024-08-29 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beltexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='disciplines',
            field=models.ManyToManyField(related_name='event_participations', to='performance.discipline'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examparameterscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.beltexam'),
        ),
        migrations.AddField(
            model_name='examparameterscore',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.evaluationparameter'),
        ),
        migrations.AddField(
            model_name='beltexam',
            name='parameters_evaluated',
            field=models.ManyToManyField(related_name='belt_exams', through='performance.ExamParameterScore', to='performance.evaluationparameter'),
        ),
        migrations.AddField(
            model_name='performancestatistics',
            name='belt_exams',
            field=models.ManyToManyField(blank=True, related_name='performance_statistics', to='performance.beltexam'),
        ),
        migrations.AddField(
            model_name='performancestatistics',
            name='event_participations',
            field=models.ManyToManyField(blank=True, related_name='performance_statistics', to='performance.eventparticipation'),
        ),
        migrations.AddField(
            model_name='performancestatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
