# Generated by Django 5.1 on 2025-02-06 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examparameterscore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examparameterscore',
            name='parameter',
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
            },
        ),
        migrations.CreateModel(
            name='ExamResultParameterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_scores', to='performance.examresult')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_scores', to='performance.evaluationparameter')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_level', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'ordering': ['exam_date'],
            },
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='performance.examsession'),
        ),
        migrations.AlterField(
            model_name='performancestatistics',
            name='belt_exams',
            field=models.ManyToManyField(blank=True, related_name='performance_statistics', to='performance.examsession'),
        ),
        migrations.DeleteModel(
            name='BeltExam',
        ),
        migrations.DeleteModel(
            name='ExamParameterScore',
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam_session', 'participant')},
        ),
    ]
