# Generated by Django 5.1 on 2025-07-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_remove_examparameterscore_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationparameter',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
