# Generated by Django 5.1 on 2025-10-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_dynamic_events_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='category',
        ),
    ]
