# Generated by Django 5.1 on 2025-11-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_examsession_evaluation_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='passed',
            field=models.BooleanField(default=False, help_text='Indica si el participante aprobó el examen', verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='belt_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BeltRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cinturón')),
                ('order_number', models.IntegerField(help_text='Número único que indica el orden del cinturón (1=Blanco, 2=Naranja, etc.)', unique=True, verbose_name='Número de Orden')),
                ('category', models.CharField(choices=[('Kyu A', 'Kyu A'), ('Kyu B', 'Kyu B'), ('Dan', 'Dan')], max_length=10, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cinturón',
                'verbose_name_plural': 'Cinturones',
                'ordering': ['order_number'],
                'indexes': [models.Index(fields=['order_number'], name='performance_order_n_d913a9_idx'), models.Index(fields=['category'], name='performance_categor_8aeb21_idx')],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='belt_rank',
            field=models.ForeignKey(blank=True, help_text='Cinturón que se evaluará en esta sesión de examen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='performance.beltrank', verbose_name='Cinturón a Evaluar'),
        ),
    ]
