# Generated by Django 5.1 on 2025-02-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen para el blog', null=True, upload_to='blog_images/'),
        ),
    ]
