# Generated by Django 5.1 on 2025-03-03 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de recurso',
                'verbose_name_plural': 'Etiquetas de recursos',
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='resource',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de descargas'),
        ),
        migrations.AddField(
            model_name='resource',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (segundos)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AddField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado'), ('ALL', 'Todos los niveles')], default='ALL', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('DOCUMENT', 'Documento'), ('LINK', 'Enlace'), ('IMAGE', 'Imagen'), ('AUDIO', 'Audio')], default='DOCUMENT', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='resource',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de vistas'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('TECHNIQUE', 'Técnica'), ('THEORY', 'Teoría'), ('HISTORY', 'Historia'), ('PHILOSOPHY', 'Filosofía'), ('TRAINING', 'Entrenamiento'), ('COMPETITION', 'Competición'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.resourcetag', verbose_name='Etiquetas'),
        ),
    ]
