# Generated by Django 5.1 on 2025-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcetag_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('KYU_A', 'Kyu A'), ('KYU_B', 'Kyu B'), ('DAN', 'Dan'), ('ALL', 'Todos los niveles')], default='ALL', max_length=20, verbose_name='Nivel'),
        ),
    ]
